name: CI (Gradle)

on:
  pull_request:
    branches: [develop]   # bloquea el PR hasta pasar checks
  push:
    branches: [develop]
permissions:
  contents: read
  checks: write
  pull-requests: write

jobs:
  lint_format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with: { distribution: temurin, java-version: "17" }
      - uses: gradle/actions/setup-gradle@v3
      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
      - name: Checkstyle + Spotless (no modifica código)
        run: |
          ./gradlew checkstyleMain checkstyleTest --no-daemon
          ./gradlew spotlessCheck --no-daemon

  unit_tests:
    runs-on: ubuntu-latest
    needs: [ lint_format ]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"
      - uses: gradle/actions/setup-gradle@v3
      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
      - name: Unit tests
        run: ./gradlew test --no-daemon
      - name: Publicar reportes (unit)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: unit-test-report
          path: build/reports/tests/test
      - name: Anotar resultados (unit) en el PR
        if: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name == github.repository }}
        uses: dorny/test-reporter@v1
        with:
          name: JUnit (unit)
          path: build/test-results/test/*.xml
          reporter: java-junit
          fail-on-error: false

  # integration_tests:
  #   runs-on: ubuntu-latest
  #   needs: [unit_tests]
  #   steps:
  #     - uses: actions/checkout@v4
  #     - uses: actions/setup-java@v4
  #       with: { distribution: temurin, java-version: "17" }
  #     - uses: gradle/actions/setup-gradle@v3
  #     - name: Run integration tests
  #       run: ./gradlew integrationTest --no-daemon
  #     - name: Upload IT report
  #       if: always()
  #       uses: actions/upload-artifact@v4
  #       with:
  #         name: integration-test-report
  #         path: build/reports/tests/integrationTest
  #     - name: Annotate IT results in PR
  #       if: always()
  #       uses: dorny/test-reporter@v1
  #       with:
  #         name: JUnit (integration)
  #         path: build/test-results/integrationTest/*.xml
  #         reporter: java-junit
  #         fail-on-error: false


  build:
    runs-on: ubuntu-latest
    needs: [ unit_tests ]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"
      - uses: gradle/actions/setup-gradle@v3

      - name: Ensure Unix line-endings (only needed if repo was edited on Windows)
        run: sed -i 's/\r$//' gradlew

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Assemble (sin re-ejecutar tests)
        run: ./gradlew assemble --no-daemon
