name: CI Java con Gradle

on:
  pull_request:
    branches: [ "develop" ]
  push:
    branches: [ "develop" ]  # opcional

jobs:
  format-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - uses: gradle/actions/setup-gradle@v4
      - name: Permisos gradlew
        run: chmod +x ./gradlew
      - name: Format check (Spotless)
        run: ./gradlew --no-daemon spotlessCheck

  unit-tests:
    runs-on: ubuntu-latest
    needs: [format-check]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - uses: gradle/actions/setup-gradle@v4
      - name: Permisos gradlew
        run: chmod +x ./gradlew
      - name: Unit tests + coverage
        run: ./gradlew --no-daemon test jacocoTestReport
      - name: Publicar reporte de tests
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: reports-unit
          path: build/reports/tests/test/index.html

  build:
    runs-on: ubuntu-latest
    needs: [unit-tests]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - uses: gradle/actions/setup-gradle@v4
      - name: Permisos gradlew
        run: chmod +x ./gradlew
      - name: Build (assemble)
        run: ./gradlew --no-daemon assemble
      - name: Publicar artefactos
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: build/libs/*
